
/*
Test the performance of methods used to check for cipher suites on the TLS 1.2
cipher suite blacklist from HTTP/2 RFC 7540.

This file was generated by make_c_test_http2_blacklist.pl.

Copyright (C) 2015 Jay Satiro <raysatiro@yahoo.com>
http://curl.haxx.se/docs/copyright.html

https://gist.github.com/jay/hash <----- REPLACE THIS WITH LINK TO REPO
https://github.com/bagder/curl/pull/406
*/

#include <stdio.h>
#include <stdlib.h>
#include <search.h>
#include <time.h>

#undef FALSE
#define FALSE 0

#undef TRUE
#define TRUE 1

struct cipher {
  int id;
  const char *name;
};

/* HTTP/2 - RFC OPTIONAL banned ciphers sorted by id */
struct cipher banned_ciphers[] = {
  { 0x00, "TLS_NULL_WITH_NULL_NULL" },
  { 0x01, "TLS_RSA_WITH_NULL_MD5" },
  { 0x02, "TLS_RSA_WITH_NULL_SHA" },
  { 0x03, "TLS_RSA_EXPORT_WITH_RC4_40_MD5" },
  { 0x04, "TLS_RSA_WITH_RC4_128_MD5" },
  { 0x05, "TLS_RSA_WITH_RC4_128_SHA" },
  { 0x06, "TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5" },
  { 0x07, "TLS_RSA_WITH_IDEA_CBC_SHA" },
  { 0x08, "TLS_RSA_EXPORT_WITH_DES40_CBC_SHA" },
  { 0x09, "TLS_RSA_WITH_DES_CBC_SHA" },
  { 0x0A, "TLS_RSA_WITH_3DES_EDE_CBC_SHA" },
  { 0x0B, "TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA" },
  { 0x0C, "TLS_DH_DSS_WITH_DES_CBC_SHA" },
  { 0x0D, "TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA" },
  { 0x0E, "TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA" },
  { 0x0F, "TLS_DH_RSA_WITH_DES_CBC_SHA" },
  { 0x10, "TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA" },
  { 0x11, "TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA" },
  { 0x12, "TLS_DHE_DSS_WITH_DES_CBC_SHA" },
  { 0x13, "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA" },
  { 0x14, "TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA" },
  { 0x15, "TLS_DHE_RSA_WITH_DES_CBC_SHA" },
  { 0x16, "TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA" },
  { 0x17, "TLS_DH_anon_EXPORT_WITH_RC4_40_MD5" },
  { 0x18, "TLS_DH_anon_WITH_RC4_128_MD5" },
  { 0x19, "TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA" },
  { 0x1A, "TLS_DH_anon_WITH_DES_CBC_SHA" },
  { 0x1B, "TLS_DH_anon_WITH_3DES_EDE_CBC_SHA" },
  { 0x1E, "TLS_KRB5_WITH_DES_CBC_SHA" },
  { 0x1F, "TLS_KRB5_WITH_3DES_EDE_CBC_SHA" },
  { 0x20, "TLS_KRB5_WITH_RC4_128_SHA" },
  { 0x21, "TLS_KRB5_WITH_IDEA_CBC_SHA" },
  { 0x22, "TLS_KRB5_WITH_DES_CBC_MD5" },
  { 0x23, "TLS_KRB5_WITH_3DES_EDE_CBC_MD5" },
  { 0x24, "TLS_KRB5_WITH_RC4_128_MD5" },
  { 0x25, "TLS_KRB5_WITH_IDEA_CBC_MD5" },
  { 0x26, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA" },
  { 0x27, "TLS_KRB5_EXPORT_WITH_RC2_CBC_40_SHA" },
  { 0x28, "TLS_KRB5_EXPORT_WITH_RC4_40_SHA" },
  { 0x29, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5" },
  { 0x2A, "TLS_KRB5_EXPORT_WITH_RC2_CBC_40_MD5" },
  { 0x2B, "TLS_KRB5_EXPORT_WITH_RC4_40_MD5" },
  { 0x2C, "TLS_PSK_WITH_NULL_SHA" },
  { 0x2D, "TLS_DHE_PSK_WITH_NULL_SHA" },
  { 0x2E, "TLS_RSA_PSK_WITH_NULL_SHA" },
  { 0x2F, "TLS_RSA_WITH_AES_128_CBC_SHA" },
  { 0x30, "TLS_DH_DSS_WITH_AES_128_CBC_SHA" },
  { 0x31, "TLS_DH_RSA_WITH_AES_128_CBC_SHA" },
  { 0x32, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA" },
  { 0x33, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA" },
  { 0x34, "TLS_DH_anon_WITH_AES_128_CBC_SHA" },
  { 0x35, "TLS_RSA_WITH_AES_256_CBC_SHA" },
  { 0x36, "TLS_DH_DSS_WITH_AES_256_CBC_SHA" },
  { 0x37, "TLS_DH_RSA_WITH_AES_256_CBC_SHA" },
  { 0x38, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA" },
  { 0x39, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA" },
  { 0x3A, "TLS_DH_anon_WITH_AES_256_CBC_SHA" },
  { 0x3B, "TLS_RSA_WITH_NULL_SHA256" },
  { 0x3C, "TLS_RSA_WITH_AES_128_CBC_SHA256" },
  { 0x3D, "TLS_RSA_WITH_AES_256_CBC_SHA256" },
  { 0x3E, "TLS_DH_DSS_WITH_AES_128_CBC_SHA256" },
  { 0x3F, "TLS_DH_RSA_WITH_AES_128_CBC_SHA256" },
  { 0x40, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256" },
  { 0x41, "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA" },
  { 0x42, "TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA" },
  { 0x43, "TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA" },
  { 0x44, "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA" },
  { 0x45, "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA" },
  { 0x46, "TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA" },
  { 0x67, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256" },
  { 0x68, "TLS_DH_DSS_WITH_AES_256_CBC_SHA256" },
  { 0x69, "TLS_DH_RSA_WITH_AES_256_CBC_SHA256" },
  { 0x6A, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256" },
  { 0x6B, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256" },
  { 0x6C, "TLS_DH_anon_WITH_AES_128_CBC_SHA256" },
  { 0x6D, "TLS_DH_anon_WITH_AES_256_CBC_SHA256" },
  { 0x84, "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA" },
  { 0x85, "TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA" },
  { 0x86, "TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA" },
  { 0x87, "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA" },
  { 0x88, "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA" },
  { 0x89, "TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA" },
  { 0x8A, "TLS_PSK_WITH_RC4_128_SHA" },
  { 0x8B, "TLS_PSK_WITH_3DES_EDE_CBC_SHA" },
  { 0x8C, "TLS_PSK_WITH_AES_128_CBC_SHA" },
  { 0x8D, "TLS_PSK_WITH_AES_256_CBC_SHA" },
  { 0x8E, "TLS_DHE_PSK_WITH_RC4_128_SHA" },
  { 0x8F, "TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA" },
  { 0x90, "TLS_DHE_PSK_WITH_AES_128_CBC_SHA" },
  { 0x91, "TLS_DHE_PSK_WITH_AES_256_CBC_SHA" },
  { 0x92, "TLS_RSA_PSK_WITH_RC4_128_SHA" },
  { 0x93, "TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA" },
  { 0x94, "TLS_RSA_PSK_WITH_AES_128_CBC_SHA" },
  { 0x95, "TLS_RSA_PSK_WITH_AES_256_CBC_SHA" },
  { 0x96, "TLS_RSA_WITH_SEED_CBC_SHA" },
  { 0x97, "TLS_DH_DSS_WITH_SEED_CBC_SHA" },
  { 0x98, "TLS_DH_RSA_WITH_SEED_CBC_SHA" },
  { 0x99, "TLS_DHE_DSS_WITH_SEED_CBC_SHA" },
  { 0x9A, "TLS_DHE_RSA_WITH_SEED_CBC_SHA" },
  { 0x9B, "TLS_DH_anon_WITH_SEED_CBC_SHA" },
  { 0x9C, "TLS_RSA_WITH_AES_128_GCM_SHA256" },
  { 0x9D, "TLS_RSA_WITH_AES_256_GCM_SHA384" },
  { 0xA0, "TLS_DH_RSA_WITH_AES_128_GCM_SHA256" },
  { 0xA1, "TLS_DH_RSA_WITH_AES_256_GCM_SHA384" },
  { 0xA4, "TLS_DH_DSS_WITH_AES_128_GCM_SHA256" },
  { 0xA5, "TLS_DH_DSS_WITH_AES_256_GCM_SHA384" },
  { 0xA6, "TLS_DH_anon_WITH_AES_128_GCM_SHA256" },
  { 0xA7, "TLS_DH_anon_WITH_AES_256_GCM_SHA384" },
  { 0xA8, "TLS_PSK_WITH_AES_128_GCM_SHA256" },
  { 0xA9, "TLS_PSK_WITH_AES_256_GCM_SHA384" },
  { 0xAC, "TLS_RSA_PSK_WITH_AES_128_GCM_SHA256" },
  { 0xAD, "TLS_RSA_PSK_WITH_AES_256_GCM_SHA384" },
  { 0xAE, "TLS_PSK_WITH_AES_128_CBC_SHA256" },
  { 0xAF, "TLS_PSK_WITH_AES_256_CBC_SHA384" },
  { 0xB0, "TLS_PSK_WITH_NULL_SHA256" },
  { 0xB1, "TLS_PSK_WITH_NULL_SHA384" },
  { 0xB2, "TLS_DHE_PSK_WITH_AES_128_CBC_SHA256" },
  { 0xB3, "TLS_DHE_PSK_WITH_AES_256_CBC_SHA384" },
  { 0xB4, "TLS_DHE_PSK_WITH_NULL_SHA256" },
  { 0xB5, "TLS_DHE_PSK_WITH_NULL_SHA384" },
  { 0xB6, "TLS_RSA_PSK_WITH_AES_128_CBC_SHA256" },
  { 0xB7, "TLS_RSA_PSK_WITH_AES_256_CBC_SHA384" },
  { 0xB8, "TLS_RSA_PSK_WITH_NULL_SHA256" },
  { 0xB9, "TLS_RSA_PSK_WITH_NULL_SHA384" },
  { 0xBA, "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xBB, "TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xBC, "TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xBD, "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xBE, "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xBF, "TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xC0, "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256" },
  { 0xC1, "TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA256" },
  { 0xC2, "TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA256" },
  { 0xC3, "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256" },
  { 0xC4, "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256" },
  { 0xC5, "TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256" },
  { 0xFF, "TLS_EMPTY_RENEGOTIATION_INFO_SCSV" },
  { 0xC001, "TLS_ECDH_ECDSA_WITH_NULL_SHA" },
  { 0xC002, "TLS_ECDH_ECDSA_WITH_RC4_128_SHA" },
  { 0xC003, "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA" },
  { 0xC004, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA" },
  { 0xC005, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA" },
  { 0xC006, "TLS_ECDHE_ECDSA_WITH_NULL_SHA" },
  { 0xC007, "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA" },
  { 0xC008, "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA" },
  { 0xC009, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA" },
  { 0xC00A, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA" },
  { 0xC00B, "TLS_ECDH_RSA_WITH_NULL_SHA" },
  { 0xC00C, "TLS_ECDH_RSA_WITH_RC4_128_SHA" },
  { 0xC00D, "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA" },
  { 0xC00E, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA" },
  { 0xC00F, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA" },
  { 0xC010, "TLS_ECDHE_RSA_WITH_NULL_SHA" },
  { 0xC011, "TLS_ECDHE_RSA_WITH_RC4_128_SHA" },
  { 0xC012, "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA" },
  { 0xC013, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA" },
  { 0xC014, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA" },
  { 0xC015, "TLS_ECDH_anon_WITH_NULL_SHA" },
  { 0xC016, "TLS_ECDH_anon_WITH_RC4_128_SHA" },
  { 0xC017, "TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA" },
  { 0xC018, "TLS_ECDH_anon_WITH_AES_128_CBC_SHA" },
  { 0xC019, "TLS_ECDH_anon_WITH_AES_256_CBC_SHA" },
  { 0xC01A, "TLS_SRP_SHA_WITH_3DES_EDE_CBC_SHA" },
  { 0xC01B, "TLS_SRP_SHA_RSA_WITH_3DES_EDE_CBC_SHA" },
  { 0xC01C, "TLS_SRP_SHA_DSS_WITH_3DES_EDE_CBC_SHA" },
  { 0xC01D, "TLS_SRP_SHA_WITH_AES_128_CBC_SHA" },
  { 0xC01E, "TLS_SRP_SHA_RSA_WITH_AES_128_CBC_SHA" },
  { 0xC01F, "TLS_SRP_SHA_DSS_WITH_AES_128_CBC_SHA" },
  { 0xC020, "TLS_SRP_SHA_WITH_AES_256_CBC_SHA" },
  { 0xC021, "TLS_SRP_SHA_RSA_WITH_AES_256_CBC_SHA" },
  { 0xC022, "TLS_SRP_SHA_DSS_WITH_AES_256_CBC_SHA" },
  { 0xC023, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256" },
  { 0xC024, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384" },
  { 0xC025, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256" },
  { 0xC026, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384" },
  { 0xC027, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256" },
  { 0xC028, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384" },
  { 0xC029, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256" },
  { 0xC02A, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384" },
  { 0xC02D, "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256" },
  { 0xC02E, "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384" },
  { 0xC031, "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256" },
  { 0xC032, "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384" },
  { 0xC033, "TLS_ECDHE_PSK_WITH_RC4_128_SHA" },
  { 0xC034, "TLS_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA" },
  { 0xC035, "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA" },
  { 0xC036, "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA" },
  { 0xC037, "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256" },
  { 0xC038, "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384" },
  { 0xC039, "TLS_ECDHE_PSK_WITH_NULL_SHA" },
  { 0xC03A, "TLS_ECDHE_PSK_WITH_NULL_SHA256" },
  { 0xC03B, "TLS_ECDHE_PSK_WITH_NULL_SHA384" },
  { 0xC03C, "TLS_RSA_WITH_ARIA_128_CBC_SHA256" },
  { 0xC03D, "TLS_RSA_WITH_ARIA_256_CBC_SHA384" },
  { 0xC03E, "TLS_DH_DSS_WITH_ARIA_128_CBC_SHA256" },
  { 0xC03F, "TLS_DH_DSS_WITH_ARIA_256_CBC_SHA384" },
  { 0xC040, "TLS_DH_RSA_WITH_ARIA_128_CBC_SHA256" },
  { 0xC041, "TLS_DH_RSA_WITH_ARIA_256_CBC_SHA384" },
  { 0xC042, "TLS_DHE_DSS_WITH_ARIA_128_CBC_SHA256" },
  { 0xC043, "TLS_DHE_DSS_WITH_ARIA_256_CBC_SHA384" },
  { 0xC044, "TLS_DHE_RSA_WITH_ARIA_128_CBC_SHA256" },
  { 0xC045, "TLS_DHE_RSA_WITH_ARIA_256_CBC_SHA384" },
  { 0xC046, "TLS_DH_anon_WITH_ARIA_128_CBC_SHA256" },
  { 0xC047, "TLS_DH_anon_WITH_ARIA_256_CBC_SHA384" },
  { 0xC048, "TLS_ECDHE_ECDSA_WITH_ARIA_128_CBC_SHA256" },
  { 0xC049, "TLS_ECDHE_ECDSA_WITH_ARIA_256_CBC_SHA384" },
  { 0xC04A, "TLS_ECDH_ECDSA_WITH_ARIA_128_CBC_SHA256" },
  { 0xC04B, "TLS_ECDH_ECDSA_WITH_ARIA_256_CBC_SHA384" },
  { 0xC04C, "TLS_ECDHE_RSA_WITH_ARIA_128_CBC_SHA256" },
  { 0xC04D, "TLS_ECDHE_RSA_WITH_ARIA_256_CBC_SHA384" },
  { 0xC04E, "TLS_ECDH_RSA_WITH_ARIA_128_CBC_SHA256" },
  { 0xC04F, "TLS_ECDH_RSA_WITH_ARIA_256_CBC_SHA384" },
  { 0xC050, "TLS_RSA_WITH_ARIA_128_GCM_SHA256" },
  { 0xC051, "TLS_RSA_WITH_ARIA_256_GCM_SHA384" },
  { 0xC054, "TLS_DH_RSA_WITH_ARIA_128_GCM_SHA256" },
  { 0xC055, "TLS_DH_RSA_WITH_ARIA_256_GCM_SHA384" },
  { 0xC058, "TLS_DH_DSS_WITH_ARIA_128_GCM_SHA256" },
  { 0xC059, "TLS_DH_DSS_WITH_ARIA_256_GCM_SHA384" },
  { 0xC05A, "TLS_DH_anon_WITH_ARIA_128_GCM_SHA256" },
  { 0xC05B, "TLS_DH_anon_WITH_ARIA_256_GCM_SHA384" },
  { 0xC05E, "TLS_ECDH_ECDSA_WITH_ARIA_128_GCM_SHA256" },
  { 0xC05F, "TLS_ECDH_ECDSA_WITH_ARIA_256_GCM_SHA384" },
  { 0xC062, "TLS_ECDH_RSA_WITH_ARIA_128_GCM_SHA256" },
  { 0xC063, "TLS_ECDH_RSA_WITH_ARIA_256_GCM_SHA384" },
  { 0xC064, "TLS_PSK_WITH_ARIA_128_CBC_SHA256" },
  { 0xC065, "TLS_PSK_WITH_ARIA_256_CBC_SHA384" },
  { 0xC066, "TLS_DHE_PSK_WITH_ARIA_128_CBC_SHA256" },
  { 0xC067, "TLS_DHE_PSK_WITH_ARIA_256_CBC_SHA384" },
  { 0xC068, "TLS_RSA_PSK_WITH_ARIA_128_CBC_SHA256" },
  { 0xC069, "TLS_RSA_PSK_WITH_ARIA_256_CBC_SHA384" },
  { 0xC06A, "TLS_PSK_WITH_ARIA_128_GCM_SHA256" },
  { 0xC06B, "TLS_PSK_WITH_ARIA_256_GCM_SHA384" },
  { 0xC06E, "TLS_RSA_PSK_WITH_ARIA_128_GCM_SHA256" },
  { 0xC06F, "TLS_RSA_PSK_WITH_ARIA_256_GCM_SHA384" },
  { 0xC070, "TLS_ECDHE_PSK_WITH_ARIA_128_CBC_SHA256" },
  { 0xC071, "TLS_ECDHE_PSK_WITH_ARIA_256_CBC_SHA384" },
  { 0xC072, "TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xC073, "TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_CBC_SHA384" },
  { 0xC074, "TLS_ECDH_ECDSA_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xC075, "TLS_ECDH_ECDSA_WITH_CAMELLIA_256_CBC_SHA384" },
  { 0xC076, "TLS_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xC077, "TLS_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384" },
  { 0xC078, "TLS_ECDH_RSA_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xC079, "TLS_ECDH_RSA_WITH_CAMELLIA_256_CBC_SHA384" },
  { 0xC07A, "TLS_RSA_WITH_CAMELLIA_128_GCM_SHA256" },
  { 0xC07B, "TLS_RSA_WITH_CAMELLIA_256_GCM_SHA384" },
  { 0xC07E, "TLS_DH_RSA_WITH_CAMELLIA_128_GCM_SHA256" },
  { 0xC07F, "TLS_DH_RSA_WITH_CAMELLIA_256_GCM_SHA384" },
  { 0xC082, "TLS_DH_DSS_WITH_CAMELLIA_128_GCM_SHA256" },
  { 0xC083, "TLS_DH_DSS_WITH_CAMELLIA_256_GCM_SHA384" },
  { 0xC084, "TLS_DH_anon_WITH_CAMELLIA_128_GCM_SHA256" },
  { 0xC085, "TLS_DH_anon_WITH_CAMELLIA_256_GCM_SHA384" },
  { 0xC088, "TLS_ECDH_ECDSA_WITH_CAMELLIA_128_GCM_SHA256" },
  { 0xC089, "TLS_ECDH_ECDSA_WITH_CAMELLIA_256_GCM_SHA384" },
  { 0xC08C, "TLS_ECDH_RSA_WITH_CAMELLIA_128_GCM_SHA256" },
  { 0xC08D, "TLS_ECDH_RSA_WITH_CAMELLIA_256_GCM_SHA384" },
  { 0xC08E, "TLS_PSK_WITH_CAMELLIA_128_GCM_SHA256" },
  { 0xC08F, "TLS_PSK_WITH_CAMELLIA_256_GCM_SHA384" },
  { 0xC092, "TLS_RSA_PSK_WITH_CAMELLIA_128_GCM_SHA256" },
  { 0xC093, "TLS_RSA_PSK_WITH_CAMELLIA_256_GCM_SHA384" },
  { 0xC094, "TLS_PSK_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xC095, "TLS_PSK_WITH_CAMELLIA_256_CBC_SHA384" },
  { 0xC096, "TLS_DHE_PSK_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xC097, "TLS_DHE_PSK_WITH_CAMELLIA_256_CBC_SHA384" },
  { 0xC098, "TLS_RSA_PSK_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xC099, "TLS_RSA_PSK_WITH_CAMELLIA_256_CBC_SHA384" },
  { 0xC09A, "TLS_ECDHE_PSK_WITH_CAMELLIA_128_CBC_SHA256" },
  { 0xC09B, "TLS_ECDHE_PSK_WITH_CAMELLIA_256_CBC_SHA384" },
  { 0xC09C, "TLS_RSA_WITH_AES_128_CCM" },
  { 0xC09D, "TLS_RSA_WITH_AES_256_CCM" },
  { 0xC0A0, "TLS_RSA_WITH_AES_128_CCM_8" },
  { 0xC0A1, "TLS_RSA_WITH_AES_256_CCM_8" },
  { 0xC0A4, "TLS_PSK_WITH_AES_128_CCM" },
  { 0xC0A5, "TLS_PSK_WITH_AES_256_CCM" },
  { 0xC0A8, "TLS_PSK_WITH_AES_128_CCM_8" },
  { 0xC0A9, "TLS_PSK_WITH_AES_256_CCM_8" }
};

/* Simple loop to check if id is banned */
int IsCipherBannedMethod0(int id)
{
  unsigned i;

  for(i = 0; i < sizeof banned_ciphers / sizeof banned_ciphers[0]; ++i) {
    if(id < banned_ciphers[i].id)
      return FALSE;
    else if(id == banned_ciphers[i].id)
      return TRUE;
  }

  return FALSE;
}

/* Conditional logic to check if id is banned */
#define IS_CIPHER_BANNED_METHOD1(id) ( \
  (0x00 <= id && id <= 0x1B) || (0x1E <= id && id <= 0x46) || \
  (0x67 <= id && id <= 0x6D) || (0x84 <= id && id <= 0x9D) || \
  id == 0xA0 || id == 0xA1 || (0xA4 <= id && id <= 0xA9) || \
  (0xAC <= id && id <= 0xC5) || id == 0xFF || \
  (0xC001 <= id && id <= 0xC02A) || id == 0xC02D || id == 0xC02E || \
  (0xC031 <= id && id <= 0xC051) || id == 0xC054 || id == 0xC055 || \
  (0xC058 <= id && id <= 0xC05B) || id == 0xC05E || id == 0xC05F || \
  (0xC062 <= id && id <= 0xC06B) || (0xC06E <= id && id <= 0xC07B) || \
  id == 0xC07E || id == 0xC07F || (0xC082 <= id && id <= 0xC085) || \
  id == 0xC088 || id == 0xC089 || (0xC08C <= id && id <= 0xC08F) || \
  (0xC092 <= id && id <= 0xC09D) || id == 0xC0A0 || id == 0xC0A1 || \
  id == 0xC0A4 || id == 0xC0A5 || id == 0xC0A8 || id == 0xC0A9 \
)

/* Conditional logic w/ lookup tables to check if id is banned */
#define IS_CIPHER_BANNED_METHOD2(id) ( \
  (0x0000 <= id && id <= 0x00FF && \
    "\xFF\xFF\xFF\xCF\xFF\xFF\xFF\xFF\x7F\x00\x00\x00\x80\x3F\x00\x00" \
    "\xF0\xFF\xFF\x3F\xF3\xF3\xFF\xFF\x3F\x00\x00\x00\x00\x00\x00\x80" \
    [(id & 0xFF) / 8] & (1 << (id % 8))) || \
  (0xC000 <= id && id <= 0xC0FF && \
    "\xFE\xFF\xFF\xFF\xFF\x67\xFE\xFF\xFF\xFF\x33\xCF\xFC\xCF\xFF\xCF" \
    "\x3C\xF3\xFC\x3F\x33\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" \
    [(id & 0xFF) / 8] & (1 << (id % 8))) \
)

int CompareCipherId(const void *id, const void *cipher)
{
  return *(int *)id < ((struct cipher *)cipher)->id ? -1 :
           *(int *)id > ((struct cipher *)cipher)->id ? 1 : 0;
}

/* Binary search to check if id is banned */
int IsCipherBannedMethod3(int id)
{
  return !!bsearch(&id, banned_ciphers,
                   sizeof banned_ciphers / sizeof banned_ciphers[0],
                   sizeof banned_ciphers[0], CompareCipherId);
}

/* Switch statement to check if id is banned */
int IsCipherBannedMethod4(int id)
{
  switch(id) {
  case 0x00: case 0x01: case 0x02: case 0x03: case 0x04:
  case 0x05: case 0x06: case 0x07: case 0x08: case 0x09:
  case 0x0A: case 0x0B: case 0x0C: case 0x0D: case 0x0E:
  case 0x0F: case 0x10: case 0x11: case 0x12: case 0x13:
  case 0x14: case 0x15: case 0x16: case 0x17: case 0x18:
  case 0x19: case 0x1A: case 0x1B: case 0x1E: case 0x1F:
  case 0x20: case 0x21: case 0x22: case 0x23: case 0x24:
  case 0x25: case 0x26: case 0x27: case 0x28: case 0x29:
  case 0x2A: case 0x2B: case 0x2C: case 0x2D: case 0x2E:
  case 0x2F: case 0x30: case 0x31: case 0x32: case 0x33:
  case 0x34: case 0x35: case 0x36: case 0x37: case 0x38:
  case 0x39: case 0x3A: case 0x3B: case 0x3C: case 0x3D:
  case 0x3E: case 0x3F: case 0x40: case 0x41: case 0x42:
  case 0x43: case 0x44: case 0x45: case 0x46: case 0x67:
  case 0x68: case 0x69: case 0x6A: case 0x6B: case 0x6C:
  case 0x6D: case 0x84: case 0x85: case 0x86: case 0x87:
  case 0x88: case 0x89: case 0x8A: case 0x8B: case 0x8C:
  case 0x8D: case 0x8E: case 0x8F: case 0x90: case 0x91:
  case 0x92: case 0x93: case 0x94: case 0x95: case 0x96:
  case 0x97: case 0x98: case 0x99: case 0x9A: case 0x9B:
  case 0x9C: case 0x9D: case 0xA0: case 0xA1: case 0xA4:
  case 0xA5: case 0xA6: case 0xA7: case 0xA8: case 0xA9:
  case 0xAC: case 0xAD: case 0xAE: case 0xAF: case 0xB0:
  case 0xB1: case 0xB2: case 0xB3: case 0xB4: case 0xB5:
  case 0xB6: case 0xB7: case 0xB8: case 0xB9: case 0xBA:
  case 0xBB: case 0xBC: case 0xBD: case 0xBE: case 0xBF:
  case 0xC0: case 0xC1: case 0xC2: case 0xC3: case 0xC4:
  case 0xC5: case 0xFF: case 0xC001: case 0xC002: case 0xC003:
  case 0xC004: case 0xC005: case 0xC006: case 0xC007: case 0xC008:
  case 0xC009: case 0xC00A: case 0xC00B: case 0xC00C: case 0xC00D:
  case 0xC00E: case 0xC00F: case 0xC010: case 0xC011: case 0xC012:
  case 0xC013: case 0xC014: case 0xC015: case 0xC016: case 0xC017:
  case 0xC018: case 0xC019: case 0xC01A: case 0xC01B: case 0xC01C:
  case 0xC01D: case 0xC01E: case 0xC01F: case 0xC020: case 0xC021:
  case 0xC022: case 0xC023: case 0xC024: case 0xC025: case 0xC026:
  case 0xC027: case 0xC028: case 0xC029: case 0xC02A: case 0xC02D:
  case 0xC02E: case 0xC031: case 0xC032: case 0xC033: case 0xC034:
  case 0xC035: case 0xC036: case 0xC037: case 0xC038: case 0xC039:
  case 0xC03A: case 0xC03B: case 0xC03C: case 0xC03D: case 0xC03E:
  case 0xC03F: case 0xC040: case 0xC041: case 0xC042: case 0xC043:
  case 0xC044: case 0xC045: case 0xC046: case 0xC047: case 0xC048:
  case 0xC049: case 0xC04A: case 0xC04B: case 0xC04C: case 0xC04D:
  case 0xC04E: case 0xC04F: case 0xC050: case 0xC051: case 0xC054:
  case 0xC055: case 0xC058: case 0xC059: case 0xC05A: case 0xC05B:
  case 0xC05E: case 0xC05F: case 0xC062: case 0xC063: case 0xC064:
  case 0xC065: case 0xC066: case 0xC067: case 0xC068: case 0xC069:
  case 0xC06A: case 0xC06B: case 0xC06E: case 0xC06F: case 0xC070:
  case 0xC071: case 0xC072: case 0xC073: case 0xC074: case 0xC075:
  case 0xC076: case 0xC077: case 0xC078: case 0xC079: case 0xC07A:
  case 0xC07B: case 0xC07E: case 0xC07F: case 0xC082: case 0xC083:
  case 0xC084: case 0xC085: case 0xC088: case 0xC089: case 0xC08C:
  case 0xC08D: case 0xC08E: case 0xC08F: case 0xC092: case 0xC093:
  case 0xC094: case 0xC095: case 0xC096: case 0xC097: case 0xC098:
  case 0xC099: case 0xC09A: case 0xC09B: case 0xC09C: case 0xC09D:
  case 0xC0A0: case 0xC0A1: case 0xC0A4: case 0xC0A5: case 0xC0A8:
  case 0xC0A9:
    return TRUE;
  }
  return FALSE;
}

void *malloc_or_die(size_t bytes)
{
  void *p;

  p = malloc(bytes);
  if(!p) {
    fprintf(stderr, "Fatal: Out of memory.\n");
    exit(EXIT_FAILURE);
  }

  return p;
}

#define ID_COUNT      10000000
#define METHOD_COUNT  5

#if METHOD_COUNT > 9
#error "Fix method name parsing for more than a single digit, see method_num"
#endif

int main(int argc, char *argv[])
{
  int i;
  int *random_ids;
  int **results;

  (void)argc;
  (void)argv;

  random_ids = malloc_or_die(ID_COUNT * sizeof *random_ids);
  results = malloc_or_die(METHOD_COUNT * sizeof *results);
  for(i = 0; i < METHOD_COUNT; ++i) {
    results[i] = malloc_or_die(ID_COUNT * sizeof **results);
  }

  printf("Generating %d random ids.\n", ID_COUNT);

  srand((unsigned)time(NULL));
  for(i = 0; i < ID_COUNT; ++i) {
    random_ids[i] = rand() & 32767;
  }

/* Call with method 0 first since we compare against that result table. */
#define TEST_METHOD(method, description) { \
  int method_num; \
  clock_t start, end; \
  \
  method_num = #method[sizeof #method - 2] - 48; \
  if(method_num < 0 || method_num >= METHOD_COUNT) { \
    fprintf(stderr, "Fatal: Unrecognized method: %s\n", #method); \
    exit(EXIT_FAILURE); \
  } \
  \
  printf("\nTesting method %d: %s: %s.\n", \
         method_num, #method, description); \
  \
  start = clock(); \
  for(i = 0; i < ID_COUNT; ++i) { \
    results[method_num][i] = method(random_ids[i]); \
  } \
  end = clock(); \
  \
  printf("%s took %f seconds.\n", \
         #method, ((double) (end - start)) / CLOCKS_PER_SEC); \
  \
  if(method_num) { \
    for(i = 0; i < ID_COUNT; ++i) { \
      if(results[0][i] != results[method_num][i]) { \
        fprintf(stderr, "Fatal: Test of method %d failed: id 0x%x is %s.\n", \
                method_num, results[method_num][i], \
                results[method_num][i] ? "TRUE" : "FALSE"); \
        exit(EXIT_FAILURE); \
      } \
    } \
  } \
}

  TEST_METHOD(IsCipherBannedMethod0, "simple loop");
  TEST_METHOD(IS_CIPHER_BANNED_METHOD1, "conditional logic");
  TEST_METHOD(IS_CIPHER_BANNED_METHOD2, "conditional logic w/ lookup tables");
  TEST_METHOD(IsCipherBannedMethod3, "binary search");
  TEST_METHOD(IsCipherBannedMethod4, "switch statement");

  return EXIT_SUCCESS;
}
